### PR TITLE
feat: add query-entries and allowed-operations arguments

### PR DESCRIPTION
**Pull request by EduSantosBrito**
## Summary

This PR introduces two new flags `--query-entries` and `--allowed-operations` to the `create` command. Both flags are optional. The query entries flag will filter the data based on [CDA](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/content-type/query-entries/console/curl) search parameters. The allowed operations flag has `["add", "delete", "update"]` as default value and allows to select which operations should run.

## Changes
- Added `--query-entries` flag to create command in `src/commands/create/index.ts.`
- Added `--allowed-operations` to create command in `src/commands/create/index.ts.`
- The `CreateChangesetContext` now includes `queryEntries` and `allowedOperations` type which is set from the `--query-entries` and `--allowed-operations` flags.
- Added the error message that returns from the Contentful API with the current error message as fallback.

This change allows users to have more control over the changesets they create by filtering using search parameters and selecting operations to be executed.

### CODE REVIEW

**Comment by EduSantosBrito** [comment]
Hey @marcolink 

I've changed the `content-type` filter to `query-entries` :)

I've also added a new parameter, `allowed-operations`. 
I needed to create a patch with only `add` operations, so I added this new options with the default operations as default value. 
I'll edit the main description/title of this PR.

**Comment by mgalassi** [comment]
Bumping this PR as this is something that is extremely useful. I sincerely believe this is the single feature that is missing to make this project stand out.

At the current state, contentful-merge only computes differences between all the entries between two environments but it is almost always more practical for us to just delete one env and recreate it from the other that using what this repo offers.

This PR does what we were forced to make internally (as a fork of this repo) in order for us to migrate specific pages between our dev environment from the production one.

We would love this to be part of the main branch, this is really huge!

**Comment by mayakarabula** [comment]
Hey, sorry for the radio silence, as you probably noticed the team efforts were shifted to other projects.
However, I agree this looks very useful, I will run the tests and try to merge it.

**Comment by mayakarabula** [comment]
could you run `npm run prettier-fix` and add `allowedOperations` to a fixture in `test/unit/fixtures/create-changeset-context-fixture.ts`?

generally, PR looks really nice, I will try to add some tests after we merge it

**Comment by EduSantosBrito** [comment]
> could you run `npm run prettier-fix` and add `allowedOperations` to a fixture in `test/unit/fixtures/create-changeset-context-fixture.ts`?
> 
> generally, PR looks really nice, I will try to add some tests after we merge it

Thanks! I will do it

**Comment by EduSantosBrito** [comment]
Hey @mayakarabula 

Done and pushed :)

**Comment by mayakarabula** [comment]
@EduSantosBrito 
awesome, thank you :) will merge when CI passes

**Review by mayakarabula — APPROVED** [review]

**Comment by mayakarabula** [comment]
@EduSantosBrito 
hey just fyi, I had to change and unify delimiter for queryEntries param, it now uses "=" everywhere

https://github.com/contentful/contentful-merge/pull/911

**Pull request merged**
